automation skip_days:
  - alias: "Irrigation skip days changed"
    trigger:
      platform: state
      entity_id: input_number.irrigation_skip_days
    action:
      service: esphome.irrigation_set_skip_days
      data:
        days: "{{ states('input_number.irrigation_skip_days') | int }}"

  - alias: "Irrigation time sensor changed"
    trigger:
      platform: state
      entity_id: sensor.skip_days
    action:
      - service: automation.turn_off
        entity_id: automation.irrigation_skip_days_changed
      - service: input_number.set_value
        entity_id: input_number.irrigation_skip_days
        data_template:
          value: "{{ states('sensor.skip_days') }}"
      - service: automation.turn_on
        entity_id: automation.irrigation_skip_days_changed
