automation zone6:
  # Inputs changed
  - alias: "Zone 6 start input changed"
    id: zone6_start_input_changed
    trigger:
      platform: state
      entity_id: input_datetime.zone6_start
    action:
      service: esphome.irrigation_set_zone_start
      data:
        zone: 6
        start: "{{ states('input_datetime.zone6_start') }}"

  # ESP Sensors changed
  - alias: "Zone 6 start sensor changed"
    id: zone6_start_sensor_changed
    trigger:
      platform: state
      entity_id: sensor.zone_6_start
    condition:
      condition: not
      conditions: "{{ is_state('sensor.zone_6_start', 'unavailable') }}"
    action:
      - service: automation.turn_off
        entity_id: automation.zone_6_start_input_changed
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zone6_start
        data:
          time: "{{ states('sensor.zone_6_start') }}"
      - service: automation.turn_on
        entity_id: automation.zone_6_start_input_changed
