automation zone1:
  # Inputs changed
  - alias: "Zone 1 start input changed"
    id: zone1_start_input_changed
    trigger:
      platform: state
      entity_id: input_datetime.zone1_start
    action:
      service: esphome.irrigation_set_zone_start
      data:
        zone: 1
        start: "{{ states('input_datetime.zone1_start') }}"

  # ESP Sensors changed
  - alias: "Zone 1 start sensor changed"
    id: zone1_start_sensor_changed
    trigger:
      platform: state
      entity_id: sensor.zone_1_start
    condition:
      condition: not
      conditions: "{{ is_state('sensor.zone_1_start', 'unavailable') }}"
    action:
      - service: automation.turn_off
        entity_id: automation.zone_1_start_input_changed
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zone1_start
        data:
          time: "{{ states('sensor.zone_1_start') }}"
      - service: automation.turn_on
        entity_id: automation.zone_1_start_input_changed
