automation zone4:
  # Inputs changed
  - alias: "Zone 4 start input changed"
    id: zone4_start_input_changed
    trigger:
      platform: state
      entity_id: input_datetime.zone4_start
    action:
      service: esphome.irrigation_set_zone_start
      data:
        zone: 4
        start: "{{ states('input_datetime.zone4_start') }}"

  # ESP Sensors changed
  - alias: "Zone 4 start sensor changed"
    id: zone4_start_sensor_changed
    trigger:
      platform: state
      entity_id: sensor.zone_4_start
    condition:
      condition: not
      conditions: "{{ is_state('sensor.zone_4_start', 'unavailable') }}"
    action:
      - service: automation.turn_off
        entity_id: automation.zone_4_start_input_changed
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zone4_start
        data:
          time: "{{ states('sensor.zone_4_start') }}"
      - service: automation.turn_on
        entity_id: automation.zone_4_start_input_changed
