automation zone2:
  # Inputs changed
  - alias: "Zone 2 start input changed"
    id: zone2_start_input_changed
    trigger:
      platform: state
      entity_id: input_datetime.zone2_start
    action:
      service: esphome.irrigation_set_zone_start
      data:
        zone: 2
        start: "{{ states('input_datetime.zone2_start') }}"

  # ESP Sensors changed
  - alias: "Zone 2 start sensor changed"
    id: zone2_start_sensor_changed
    trigger:
      platform: state
      entity_id: sensor.zone_2_start
    condition:
      condition: not
      conditions: "{{ is_state('sensor.zone_2_start', 'unavailable') }}"
    action:
      - service: automation.turn_off
        entity_id: automation.zone_2_start_input_changed
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zone2_start
        data:
          time: "{{ states('sensor.zone_2_start') }}"
      - service: automation.turn_on
        entity_id: automation.zone_2_start_input_changed
