automation zone1:
  # Inputs changed
  - alias: "Zone 1 start input changed"
    trigger:
      platform: state
      entity_id: input_datetime.zone1_start
    action:
      service: esphome.irrigation_set_zone_start
      data:
        zone: 1
        start: "{{ states('input_datetime.zone1_start') }}"

  - alias: "Zone 1 duration input changed"
    trigger:
      platform: state
      entity_id: input_number.zone1_duration
    action:
      service: esphome.irrigation_set_zone_duration
      data:
        zone: 1
        duration: "{{ states('input_number.zone1_duration') | int }}"

  # ESP Sensors changed
  - alias: "Zone 1 start sensor changed"
    trigger:
      platform: state
      entity_id: sensor.zone_1_start
    action:
      - service: automation.turn_off
        entity_id: automation.zone_1_start_input_changed
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zone1_start
        data:
          time: "{{ states('sensor.zone_1_start') }}"
      - service: automation.turn_on
        entity_id: automation.zone_1_start_input_changed

  - alias: "Zone 1 duration sensor changed"
    trigger:
      platform: state
      entity_id: sensor.zone_1_duration
    action:
      - service: automation.turn_off
        entity_id: automation.zone_1_duration_input_changed
      - service: input_number.set_value
        entity_id: input_number.zone1_duration
        data_template:
          value: "{{ states('sensor.zone_1_duration') | int }}"
      - service: automation.turn_on
        entity_id: automation.zone_1_duration_input_changed
