automation zone3:
  # Inputs changed
  - alias: "Zone 3 start input changed"
    trigger:
      platform: state
      entity_id: input_datetime.zone3_start
    action:
      service: esphome.irrigation_set_zone_start
      data:
        zone: 3
        start: "{{ states('input_datetime.zone3_start') }}"

  - alias: "Zone 3 duration input changed"
    trigger:
      platform: state
      entity_id: input_number.zone3_duration
    action:
      service: esphome.irrigation_set_zone_duration
      data:
        zone: 3
        duration: "{{ states('input_number.zone3_duration') | int }}"

  # ESP Sensors changed
  - alias: "Zone 3 start sensor changed"
    trigger:
      platform: state
      entity_id: sensor.zone_3_start
    action:
      - service: automation.turn_off
        entity_id: automation.zone_3_start_input_changed
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zone3_start
        data:
          time: "{{ states('sensor.zone_3_start') }}"
      - service: automation.turn_on
        entity_id: automation.zone_3_start_input_changed

  - alias: "Zone 3 duration sensor changed"
    trigger:
      platform: state
      entity_id: sensor.zone_3_duration
    action:
      - service: automation.turn_off
        entity_id: automation.zone_3_duration_input_changed
      - service: input_number.set_value
        entity_id: input_number.zone3_duration
        data_template:
          value: "{{ states('sensor.zone_3_duration') | int }}"
      - service: automation.turn_on
        entity_id: automation.zone_3_duration_input_changed
