automation zone5:
  # Inputs changed
  - alias: "Zone 5 start input changed"
    id: zone5_start_input_changed
    trigger:
      platform: state
      entity_id: input_datetime.zone5_start
    action:
      service: esphome.irrigation_set_zone_start
      data:
        zone: 5
        start: "{{ states('input_datetime.zone5_start') }}"

  # ESP Sensors changed
  - alias: "Zone 5 start sensor changed"
    id: zone5_start_sensor_changed
    trigger:
      platform: state
      entity_id: sensor.zone_5_start
    condition:
      condition: not
      conditions: "{{ is_state('sensor.zone_5_start', 'unavailable') }}"
    action:
      - service: automation.turn_off
        entity_id: automation.zone_5_start_input_changed
      - service: input_datetime.set_datetime
        entity_id: input_datetime.zone5_start
        data:
          time: "{{ states('sensor.zone_5_start') }}"
      - service: automation.turn_on
        entity_id: automation.zone_5_start_input_changed
