sensor:
  - platform: time_date
    display_options:
      - "time"

input_datetime:
  zone1_start:
    name: Zone 1 start
    has_time: true

  zone2_start:
    name: Zone 2 start
    has_time: true

  zone3_start:
    name: Zone 3 start
    has_time: true

  zone4_start:
    name: Zone 4 start
    has_time: true

  zone5_start:
    name: Zone 5 start
    has_time: true

  zone6_start:
    name: Zone 6 start
    has_time: true
